version: "3.3"

services:
  ldap-service:
    image: odk/openldap
    deploy:
      replicas: 1
    networks:
      - ldap-network
    volumes:
      - ldap-vol:/var/lib/ldap
      - ldap-slapd.d-vol:/etc/ldap/slapd.d
    env_file:
      - ldap.env
  phpldapadmin:
    image: odk/phpldapadmin
    deploy:
      replicas: 1
    ports:
      - "${PHP_LDAPADMIN_PORT:-40000}:443"
    networks:
      - ldap-network
    env_file:
      - ldap.env
  dashboard:
    image: ccis/dashboard
    networks:
      - dashboard-network
      - sync-network
    ports:
      - 444:443
    env_file:
      - dashboard.env
  dashboard-database:
    image: ccis/dashboard-db
    networks:
      - dashboard-network
    volumes:
      - dashboard-db-vol:/var/lib/postgresql/data
    env_file:
      - dashboard-database.env
  data-sync:
    image: db-sync
    networks:
      - sync-network
      - dashboard-network
    ports:
      - 5432:5432
   configs:
     - source: ccdbsync.config
       target: config/config.txt
  nginx:
    image: nginx:1.21.3
    networks:
      - sync-network
      - dashboard-network
    ports:
      - 80:80
      - 443:443
    configs:
      - source: com.nginx.sync-endpoint.conf
        target: /etc/nginx/conf.d/default.conf
      - source: com.nginx.proxy_buffer.conf
        target: /etc/nginx/conf.d/proxy_buffer.conf
      - com.nginx.ssl_certificate
    secrets:
      - com.nginx.ssl_certificate_key

networks:
  ldap-network:
    external: 
       name: odk-x-ldap-network
  sync-network:
    external: 
       name: odk-x-sync-network
  dashboard-network:
    driver: overlay
    driver_opts:
      encrypted: ""
    internal: true

volumes:
  dashboard-db-vol: # preserve dashboard's copy of the db
  # these 2 need to be removed together
  ldap-vol: # preserve ldap db
  ldap-slapd.d-vol: # preserve ldap settings

configs:
  ccdbsync.config:
    file: ./config.txt
  com.nginx.sync-endpoint.conf:
    file: ./config/nginx/sync-endpoint-https.conf.odkdemo-nginx
  com.nginx.proxy_buffer.conf:
    file: ./config/nginx/proxy_buffer.conf
  com.nginx.ssl_certificate:
    external:
      name: odkdemo.gr.fullchain.pem
    
 secrets:
  com.nginx.ssl_certificate_key:
    external: 
      name: odkdemo.gr.privkey.pem

